### ISSUE TITLE
感觉没办法定位，数据库内容也分享一下呗

### ISSUE THREAD

**Issue by NRD90M** [GLaxky/party_history_WeiXin#1]

**Comment by GLaxky** [comment]
我分享了一些csv文件，可以导入微信小程序开发工具的云开发数据库中

**Comment by NRD90M** [comment]
那开始探索，选择人物之后，就到非洲了，后续也没法操作咋整

**Comment by GLaxky** [comment]
你也不给个报错信息的截图，我也不知道出现什么错误
或者你是只是想浏览一下功能的话我这边有一个小程序的二维码，你扫码就可以看到
![小程序二维码](https://user-images.githubusercontent.com/55688571/132184690-ac140dcc-99a6-45f2-a3ca-36994e7e6777.png)

**Comment by NRD90M** [comment]
![微信图片_20210906162911](https://user-images.githubusercontent.com/30235128/132187531-fdda2c5e-ab9f-4e68-a2b4-30baabb1e1e3.jpg)
我看了你的小程序，这里是可以显示的，我的就不行

**Comment by GLaxky** [comment]
1. 你将那三个表导入云开发数据库了吗（一共需要一下这些表![M{7@SU7{S{V@V90_53P44YB](https://user-images.githubusercontent.com/55688571/132189543-73da33b9-1e66-4281-b378-c30460ae5f8f.png)【其中，除了association、place、character外，其他的初始都是空表】
2. 而且麻烦你贴一下微信开发者工具的报错截图【我猜可能是和云开发相关的，因为代码中有我的云环境ID，这里需要修改成你的云环境ID
3. 还有就是可以问下你需要我这个项目做啥用吗？因为这个项目是我们要参加一个比赛的，可能不能直接复制给你
4. 我也是开发小白，很多我也不太懂，只能说能帮就帮

**Comment by NRD90M** [comment]
我就想把自己公众号上关联一个关于党史的小程序，不会参加比赛也不会营利，我也是新手，确实数据库没导入其他的也没改，因为好久没用开发工具好像好多东西都收费了，我再研究一下

**Comment by NRD90M** [comment]
![微信图片_20210906190832](https://user-images.githubusercontent.com/30235128/132222773-6cde085b-142a-4c11-ace2-357e765e04a3.jpg)
感觉还是缺少东西，截图给你看一下

**Comment by NRD90M** [comment]
![微信截图_20210906211357](https://user-images.githubusercontent.com/30235128/132222893-e3cffb1d-6bf0-48e3-bb40-3c477f4d5bf4.png)
上传错了，不好意思，点击气泡没内容，报错

**Comment by GLaxky** [comment]
1. 看你的报错似乎是云函数没有上传到你的云开发环境里
![4TR_J5`~BPF~W$NY0C))}9R](https://user-images.githubusercontent.com/55688571/132281453-63c11a06-21ab-475a-96b3-bd118fa24095.png)
你把cloudFunction里的云函数都上传上去，可以参考_微信官方文档_
2. 每个项目都有唯一的云环境ID，如图
![2D6H@N4`0P9NY{7( 6}9N5L](https://user-images.githubusercontent.com/55688571/132281553-9ea3d639-df35-4699-9d7d-11265772bfd6.png)
我的是cloud-environment-6e21xvc5d21990
然后我的代码中有出现这个，如图
![53RM J)2L$E0)12W9GWJ~BV](https://user-images.githubusercontent.com/55688571/132281627-b99089de-da95-4fe0-bb0b-ac27148e8242.png)
你最好把这些地方改成你的云环境ID
3. 那个你的截图中uploadCloudFunction.bat文件中的cloud-0g..是我们这个项目之前用的云环境ID，但我百度一圈，没找到什么解决方法，应该也是和云环境ID有关的（总之你先按前面两点来改改试试吧

**Comment by NRD90M** [comment]
兄弟，解决了，就是云环境id，感谢
